Repository ittovate/demo-mongo-crud, pull requests merged in 2024-09, with the labels that each got.

#1 Enforce Checkstyle Code Quality Rules
  config/.pre-commit-config.yaml
  config/checkstyle/checkstyle_changelog.md
  config/checkstyle/sun_checks.xml
  config/checkstyle/sun_checks_custom.xml
  pom.xml
  src/main/java/com/mongodb/crud/CrudApplication.java
  src/main/java/com/mongodb/crud/controller/TaskController.java
  src/main/java/com/mongodb/crud/entity/Task.java
  src/main/java/com/mongodb/crud/repository/TaskRepository.java
  src/main/java/com/mongodb/crud/service/TaskService.java
  src/main/java/com/redis/crud/RediscrudappApplication.java
  src/main/resources/application.properties
Labels: enhancement, refactor

#2 Add docker compose for MongoDB
  docker-compose.yml
  src/main/resources/application.yaml
Labels: enhancement

#3 Move Secrets to `.env`
  .gitignore
  docs/README.md
  pom.xml
  src/main/resources/application.yaml
  src/main/resources/keys.env
Labels: documentation, enhancement

#5 Create `ci.yml`
  .github/workflows/ci.yml
Labels: enhancement

#6 Chores
  config/.pre-commit-config.yaml
  docker-compose.yml
Labels: refactor

#7 Complete CRUD
  src/main/java/com/mongodb/crud/controller/TaskController.java
  src/main/java/com/mongodb/crud/entity/Task.java
  src/main/java/com/mongodb/crud/exception/GlobalExceptionHandler.java
  src/main/java/com/mongodb/crud/exception/ResourceNotFoundException.java
  src/main/java/com/mongodb/crud/repository/TaskRepository.java
  src/main/java/com/mongodb/crud/service/TaskService.java
  src/main/java/com/mongodb/crud/util/ApiResponse.java
  src/main/resources/application.yaml
Labels: enhancement, refactor

#8 Fix exception handling propagation in aspect
  src/main/java/com/mongodb/crud/aspect/LoggingAspect.java
Labels: bug

#9 Add More Exception Handling
  src/main/java/com/mongodb/crud/constant/ExceptionConstant.java
  src/main/java/com/mongodb/crud/controller/TaskController.java
  src/main/java/com/mongodb/crud/exception/DuplicateResourceException.java
  src/main/java/com/mongodb/crud/exception/GlobalExceptionHandler.java
  src/main/java/com/mongodb/crud/service/TaskService.java
Labels: enhancement, refactor

#10 Update Docs
  docs/Checkstyle Sun Checks Changelog.md
  docs/README.md
Labels: documentation

#11 Refactor Task Service
  src/main/java/com/mongodb/crud/constant/ExceptionConstant.java
  src/main/java/com/mongodb/crud/entity/Task.java
  src/main/java/com/mongodb/crud/exception/GlobalExceptionHandler.java
  src/main/java/com/mongodb/crud/exception/NullResourceException.java
  src/main/java/com/mongodb/crud/service/TaskService.java
  src/main/java/com/mongodb/crud/util/ServiceUtil.java
Labels: enhancement, refactor

#12 Add Tests for Task Service
  src/main/java/com/mongodb/crud/service/TaskService.java
  src/test/java/com/mongodb/crud/CrudApplicationTests.java
  src/test/java/com/mongodb/crud/service/TaskServiceTest.java
Labels: test

#13 Add API Docs with Swagger with Refactoring
  pom.xml
  src/main/java/com/mongodb/crud/CrudApplication.java
  src/main/java/com/mongodb/crud/config/SwaggerConfig.java
  src/main/java/com/mongodb/crud/constant/ApiResponseConstant.java
  src/main/java/com/mongodb/crud/constant/HttpConstant.java
  src/main/java/com/mongodb/crud/constant/SwaggerConstant.java
  src/main/java/com/mongodb/crud/controller/TaskController.java
  src/test/java/com/mongodb/crud/service/TaskServiceTest.java
Labels: documentation, refactor

#14 Update README.md with video demo
  docs/README.md
Labels: documentation

#15 Remove `NullResourceException` as it is Not Used
  src/main/java/com/mongodb/crud/constant/ExceptionConstant.java
  src/main/java/com/mongodb/crud/exception/GlobalExceptionHandler.java
  src/main/java/com/mongodb/crud/exception/NullResourceException.java
  src/main/java/com/mongodb/crud/service/TaskService.java
  src/main/java/com/mongodb/crud/util/ServiceUtil.java
  src/test/java/com/mongodb/crud/service/TaskServiceTest.java
Labels: refactor

#16 Fix Service Update to Handle Invalid Task Name
  src/main/java/com/mongodb/crud/config/SwaggerConfig.java
  src/main/java/com/mongodb/crud/constant/SwaggerConstant.java
  src/main/java/com/mongodb/crud/controller/TaskController.java
  src/main/java/com/mongodb/crud/service/TaskService.java
  src/test/java/com/mongodb/crud/service/TaskServiceTest.java
Labels: bug, documentation, enhancement, test

#17 Refactor Demo
  src/main/java/com/mongodb/crud/aspect/LoggingAspect.java
  src/main/java/com/mongodb/crud/config/SwaggerConfig.java
  src/main/java/com/mongodb/crud/constant/APIResponseConstant.java
  src/main/java/com/mongodb/crud/constant/AspectConstant.java
  src/main/java/com/mongodb/crud/constant/ExceptionConstant.java
  src/main/java/com/mongodb/crud/constant/HTTPConstant.java
  src/main/java/com/mongodb/crud/constant/SwaggerConstant.java
  src/main/java/com/mongodb/crud/controller/TaskController.java
  src/main/java/com/mongodb/crud/exception/GlobalExceptionHandler.java
  src/main/java/com/mongodb/crud/log/LoggingAspect.java
  src/main/java/com/mongodb/crud/util/APIResponse.java
  src/main/java/com/mongodb/crud/util/APIResponseUtil.java
  src/main/java/com/mongodb/crud/util/ApiResponse.java
  src/main/java/com/mongodb/crud/util/AspectUtil.java
  src/main/java/com/mongodb/crud/util/ServiceUtil.java
Labels: refactor
